### ISSUE TITLE
Investigate implications of `experimentalRunAllSpecs`

### ISSUE THREAD

**Issue by badeball** [badeball/cypress-cucumber-preprocessor#948]
Cypress introduced a new way of running all specs some time ago. [This](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689#issuecomment-1435729309) indicates that it's causing some issues, seemingly because of browser reloading. This should be investigated.

**Comment by pat-convex** [comment]
hello,

i wanted to open a new ticket but i saw one is open already. i get this error when i try to run all specs.

Expected to find internal spec properties with reference = dff4e7d1-2c57-44e0-a786-723f2930ead2 (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)



Because this error occurred during a after each hook we are skipping all of the remaining tests.


FYI: I have no after each hook in my test framework. i only have beforeEach hook.

**Comment by Michsior14** [comment]
Same here, without any before/after hooks.

```
index-7b2dcc9d.js:104125 Error: Expected to find internal spec properties with reference = c1637d3d-965f-4e85-b289-7beb26a8dfe8 (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
    at createError (tests?p=src/integration/app/app.feature:8734:16)
    at fail (tests?p=src/integration/app/app.feature:8738:15)
    at assert (tests?p=src/integration/app/app.feature:8745:9)
    at assertAndReturn (tests?p=src/integration/app/app.feature:8749:9)
    at retrieveInternalSpecProperties (tests?p=src/integration/app/app.feature:9929:49)
    at Context.eval (tests?p=src/integration/app/app.feature:10315:30)
```

**Comment by mysticdevx** [comment]
Hi, I am also facing this issue, and I started getting this issue after upgrading from:
v15.0.0 was fine
v15.1.4 started getting this,
(more info:
cypress: 12.7
node: 14.20.1)

**Comment by KaiWissel** [comment]
Can confirm
Node 18.14.2
Cypress 11.2.0
cypress-cucumber-preprocessor 15.1.4
cypress-esbuild-preprocessor 2.2.0

**Comment by fhemery** [comment]
> hello,
> 
> i wanted to open a new ticket but i saw one is open already. i get this error when i try to run all specs.
> 
> Expected to find internal spec properties with reference = dff4e7d1-2c57-44e0-a786-723f2930ead2 (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

I have narrowed the problem down to find out when it started to fail.
* `15.1.1` works fine
* `15.1.2` is failing

Note that this is not linked to a cypress update. I upgraded cypress from `^11.2.0` to `^12.2.0` and it works perfectly with version `15.1.1` of the plugin

So I'll stay on `15.1.1` for now.

Hope this helps :)

**Comment by marivicdbp** [comment]
Same here. I encountered the same issue. 
Currently running test on cypress v12.8.1 and tests only stops failing when plugin was updated from 15.1.1 to higher version.

**Comment by badeball** [comment]
I've released v16.0.0 which contains some fixes targeting this, check it out.

**Comment by marivicdbp** [comment]
🌮  Thanks! I downloaded v16.0.0 and has verified fix is working.

**Comment by marivicdbp** [comment]
Not sure if related though., when you run by tags, i encounter this issue: 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/86334356/227879501-ce91b071-451f-45c8-b1d9-a6293c29674a.png">

**Comment by badeball** [comment]
You have to provide an example that reproduces the problem.

**Comment by SimonGiraudMVMS** [comment]
I still have the issue when the test have a Background, exemple : 

```
Feature: Add a delivery address

Background:
Given I visit the homepage
When I sign up as a customer "qa"

Scenario: I add a delivery address from my account
Given I visit my account
And I go to my addresses
And I click on "new address"
And I fill out the new address form
And I submit the new address form
Then My address is successfully created

Scenario: I add a delivery address from the checkout tunnel for the first time
Given I visit my account
When I build a cart with the product "Product auto tour"
And I confirm my cart
And I choose the delivery option
And I fill out the new address form in the checkout tunnel
And I submit the new address form in the checkout tunnel
Then My address is successfully created, and I see a delivery option
```

When I run all test, the firsts are good, but when I have BG, the error happen, and don't run other specs

**Comment by badeball** [comment]
@SimonGiraudMVMS, you need to prove a [reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case).

**Comment by SimonGiraudMVMS** [comment]
```
Background:
Given I visit the homepage


export class HomePage {    
  static visit(){   
    cy.visit(https://www.google.com/)
   }  
  }  

Scenario: first search
When I type "blue" in the search bar
And I click on search button
Then I see results for "blue" search


Scenario: second search
When I type "red" in the search bar
And I click on search button
Then I see results for "red" search

export class Search{    
  static typeSearchInput(){       
    cy.get(inputsearch).type("color")
   }  

  static clickOnSearchButton(){       
    cy.get(searchbutton).click()
   }  

  static searchIsValide(){   
    cy.get("body").contains("color")
   }  
  }  

```


Here an exemple of a test I can do and won't work cause the Background
You can run any test; the result will be the same. The code has nothing to do with it.

**Comment by badeball** [comment]
This is not what I mean by [reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) and I can't reproduce any issue using your information. There are specific reasons for why I ask for this and I'm not going to involve myself any further until you can provide it.

**Comment by badeball** [comment]
Closing as this hasn’t produced a single actionable item.

**Comment by AlbaSS18** [comment]
I have found a similar issue. Have anyone solved? 

My setup is:
- `@badeball/cypress-cucumber-preprocessor`: ^16.0.0
- `@cypress/webpack-preprocessor`: ^6.0.2
-   `cypress`: 11.2.0
